name: Generate new version

on:
  workflow_dispatch:
    inputs:
      semver:
        description: "Version increment"
        required: true
        default: patch
        type: choice
        options:
        - major
        - minor
        - patch

jobs:
  generate-tag:
    runs-on: ubuntu-latest
    outputs:
      tagVersion: ${{ steps.tagGen.outputs.new_tag }}
      npmVersion: ${{ steps.tagGen.outputs.new_version }}
    steps:
      - uses: step-security/harden-runner@v1.4.5
        with:
          egress-policy: audit
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Bump version and push tag
        id: tagGen
        uses: hennejg/github-tag-action@v4.3.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ inputs.semver }}
          release_branches: ${{  github.ref_name }}
          dry_run: true
  build-bindings:
    needs: generate-tag
    strategy:
      fail-fast: true
      matrix:
        os: [windows-latest]
        win-target-ver: [10v1903, 10v21H1, 11v21H2, 11v22H2]
        include:
          - win-target-ver: 10v1903
            win-target-build-ver: 18362
          - win-target-ver: 10v21H1
            win-target-build-ver: 20348
          - win-target-ver: 11v21H2
            win-target-build-ver: 22000
          - win-target-ver: 11v22H2
            win-target-build-ver: 22621
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: GuillaumeFalourd/setup-windows10-sdk-action@v1.7
        with:
          sdk-version: ${{ matrix.win-target-build-ver }}
      
      - run: ls -la "C:/Program Files (x86)/Windows Kits/10/UnionMetadata"
        shell: bash

      # .NET 4.x is already installed in windows image
      # https://github.com/actions/runner-images/blob/main/images/win/Windows2019-Readme.md#net-framework
      # https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md#net-framework
      # - uses: actions/setup-dotnet@v2
      #   with:
      #     dotnet-version: '4.5.x'

      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          check-latest: true
      - run: npm install --global --fund=false node-gyp

      - uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: '[17,18)'
          msbuild-architecture: x64

      - run: dotnet build NodeRTCmd --configuration Debug
        working-directory: ./src
        
      - run: ls -la "../src/NodeRTCmd/bin/Debug"
        shell: bash
        working-directory: ./scripts
  generate-release:
    needs: generate-tag
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@v1.4.5
        with:
          egress-policy: audit
      - uses: actions/checkout@v3
      # - uses: softprops/action-gh-release@v1
      #   with:
      #     tag_name: ${{ needs.generate-tag.outputs.tagVersion }}
      #     fail_on_unmatched_files: false
      #     generate_release_notes: true
  publish-bindings:
    needs: [build-bindings, generate-release]
    strategy:
      fail-fast: true
      matrix:
        win-target-ver: [10v1903, 10v21H1, 11v21H2, 11v22H2]
        include:
          - win-target-ver: 10v1903
            win-target-build-ver: 18362
            npm-org: nodert-win10-19h1
            npm-win-major: 10
            npm-win-minor: 1903
            npm-win-desc: Codename 19H1 / May 2019 Update
          - win-target-ver: 10v21H1
            win-target-build-ver: 20348
            npm-org: nodert-win10-21h1
            npm-win-major: 10
            npm-win-minor: 21H1
            npm-win-desc: May 2021 Update
          - win-target-ver: 11v21H2
            win-target-build-ver: 22000
            npm-org: nodert-win11
            npm-win-major: 11
            npm-win-minor: 21H2
            npm-win-desc: Original Release
          - win-target-ver: 11v22H2
            win-target-build-ver: 22621
            npm-org: nodert-win11-22h2
            npm-win-major: 11
            npm-win-minor: 22H2
            npm-win-desc: September 2022 Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.npm-org }}