name: Generate new version

on:
  workflow_dispatch:
    inputs:
      semver:
        description: "Version increment"
        required: true
        default: patch
        type: choice
        options:
        - major
        - minor
        - patch

jobs:
  generate-tag:
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{ steps.tagGen.outputs.changelog }}
      tagVersion: ${{ steps.tagGen.outputs.new_tag }}
      npmVersion: ${{ steps.tagGen.outputs.new_version }}
    steps:
      - uses: step-security/harden-runner@v1.4.5
        with:
          egress-policy: audit
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Bump version and push tag
        id: tagGen
        uses: hennejg/github-tag-action@v4.3.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ inputs.semver }}
          release_branches: ${{  github.ref_name }}
  build-bindings:
    needs: generate-tag
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        win-target-ver: [10v1903, 10v21H1, 11v21H2, 11v22H2]
        include:
          - win-target-ver: 10v1903
            win-target-build-ver: 18362
          - win-target-ver: 10v21H1
            win-target-build-ver: 20348
          - win-target-ver: 11v21H2
            win-target-build-ver: 22000
          - win-target-ver: 11v22H2
            win-target-build-ver: 22621
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: GuillaumeFalourd/setup-windows10-sdk-action@v1.7
        with:
          sdk-version: ${{ matrix.win-target-build-ver }}

      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          check-latest: true
      - run: npm install --global node-gyp
  # generate-release:
  #   needs: generate-tag
  #   permissions:
  #     contents: write
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: step-security/harden-runner@v1.4.5
  #       with:
  #         egress-policy: audit
  #     - uses: actions/checkout@v3
  #     - uses: softprops/action-gh-release@v1
  #       with:
  #         body: ${{ needs.generate-tag.outputs.changelog }}
  #         tag_name: ${{ needs.generate-tag.outputs.tagVersion }}
  #         fail_on_unmatched_files: false
  #         generate_release_notes: false